CREATE DATABASE db_goo;
GRANT ALL PRIVILEGES ON *.* TO u_goo@localhost IDENTIFIED BY 'mA64nCnGqZopgd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO u_goo@'%'       IDENTIFIED BY 'mA64nCnGqZopgd' WITH GRANT OPTION;

